### ISSUE TITLE
Improve commit filtering

### ISSUE THREAD

**Issue by austinjones** [austinjones/homebrew-taps#4]
https://ryangjchandler.co.uk/articles/running-github-actions-for-certain-commit-messages

**Comment by austinjones** [comment]
```
jobs:
  format:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')"
```
